import { Service, PortfolioItem, CaseStudy, Skill, Tool, Certification, Testimonial, BlogPost, Stat, TimelineEvent } from '@/types'

export const siteConfig = {
  name: 'Yubik Darlami Thapa',
  title: 'Digital Marketing Portfolio',
  tagline: 'Performance Marketing That Delivers Results',
  description: 'Meta Ads Specialist • Content Strategist • AI Marketing Expert',
  email: 'yubikdarlamithapa@gmail.com',
  phone: '+977 9811492192',
  whatsapp: '+977 9811492192',
  calendly: 'https://calendly.com/yourname',
  social: {
    linkedin: 'https://linkedin.com/in/yourname',
    // twitter: 'https://x.com/yourname',
    instagram: 'https://instagram.com/yourname',
    facebook: 'https://facebook.com/yourname',
    github: 'https://github.com/yourname',
  },
  availability: 'Available for projects',
  location: 'Butwal, Nepal',
}

export const services: Service[] = [
  {
    id: 'meta-ads',
    title: 'Meta Ads',
    description: 'High-performing Facebook & Instagram ad campaigns that drive conversions and scale your business.',
    icon: 'Facebook',
    details: ['Campaign Strategy', 'Audience Research', 'Creative Testing', 'Pixel Setup', 'Retargeting', 'Reporting'],
    href: '/services/meta-ads',
  },
  {
    id: 'google-ads',
    title: 'Google Ads',
    description: 'Search, Display, Shopping & Performance Max campaigns optimized for maximum ROAS.',
    icon: 'Search',
    details: ['Search Campaigns', 'Display Advertising', 'Shopping Ads', 'Performance Max', 'Remarketing'],
    href: '/services/google-ads',
  },
  {
    id: 'seo',
    title: 'SEO',
    description: 'Data-driven SEO strategies that increase organic visibility and drive qualified traffic.',
    icon: 'LineChart',
    details: ['Keyword Research', 'Technical SEO', 'On-page SEO', 'Local SEO', 'Link Building'],
    href: '/services/seo',
  },
  {
    id: 'social-media',
    title: 'Social Media Marketing',
    description: 'Engaging content strategies that build communities and drive brand awareness.',
    icon: 'Share2',
    details: ['Content Strategy', 'Community Management', 'Influencer Marketing', 'Social Listening'],
    href: '/services/social-media',
  },
  {
    id: 'content-marketing',
    title: 'Content Marketing',
    description: 'Compelling content that tells your story and converts readers into customers.',
    icon: 'FileText',
    details: ['Blog Writing', 'Content Calendar', 'Copywriting', 'Email Marketing'],
    href: '/services/content-marketing',
  },
  {
    id: 'ai-marketing',
    title: 'AI Marketing',
    description: 'Leverage AI tools and automation to optimize campaigns and personalize experiences.',
    icon: 'Brain',
    details: ['AI Strategy', 'Chatbot Setup', 'Personalization', 'Marketing Automation'],
    href: '/services/ai-marketing',
  },
  {
    id: 'marketing-strategy',
    title: 'Marketing Strategy',
    description: 'Comprehensive marketing plans aligned with your business goals and target audience.',
    icon: 'Target',
    details: ['Market Research', 'Competitor Analysis', 'Growth Strategy', 'Budget Planning'],
    href: '/services/marketing-strategy',
  },
  {
    id: 'video-marketing',
    title: 'Video Marketing',
    description: 'Short-form video content optimized for TikTok, Reels, and YouTube engagement.',
    icon: 'Video',
    details: ['Script Writing', 'Reel Ideas', 'Video Editing', 'Voice-over Planning'],
    href: '/services/video-marketing',
  },
  {
    id: 'analytics',
    title: 'Marketing Analytics',
    description: 'Data analysis and reporting to track KPIs and optimize campaign performance.',
    icon: 'BarChart3',
    details: ['GA4 Setup', 'Dashboard Creation', 'Conversion Tracking', 'Performance Reports'],
    href: '/services/analytics',
  },
  {
    id: 'landing-pages',
    title: 'Landing Page Optimisation',
    description: 'Conversion-focused landing pages designed to maximize lead generation.',
    icon: 'Layout',
    details: ['A/B Testing', 'CRO Strategy', 'UX Optimization', 'CTA Optimization'],
    href: '/services/landing-pages',
  },
]

export const portfolioItems: PortfolioItem[] = [
  {
    id: 'ecom-brand-x',
    title: 'E-commerce Brand Scaling',
    industry: 'E-commerce',
    goal: 'Scale revenue profitably with Meta Ads',
    strategy: 'Implement CBO with dynamic creative testing and broad targeting',
    results: ['3.5x ROAS', '200% increase in revenue', '45% lower CPA'],
    image: '/portfolio/ecom.jpg',
    category: 'Meta Ads',
    tags: ['Meta Ads', 'E-commerce', 'Scaling'],
  },
  {
    id: 'local-restaurant',
    title: 'Local Restaurant Growth',
    industry: 'Restaurant',
    goal: 'Drive foot traffic and online orders',
    strategy: 'Geo-targeted ads with special offer creatives',
    results: ['150% increase in foot traffic', '300+ online orders/month', '2.8x ad spend return'],
    image: '/portfolio/restaurant.jpg',
    category: 'Meta Ads',
    tags: ['Meta Ads', 'Local Business', 'Restaurant'],
  },
  {
    id: 'hotel-booking',
    title: 'Hotel Direct Bookings',
    industry: 'Hospitality',
    goal: 'Increase direct website bookings',
    strategy: 'Google Hotel Ads + Search Campaign optimization',
    results: ['240% more direct bookings', '60% lower cost per booking', '4.2x ROAS'],
    image: '/portfolio/hotel.jpg',
    category: 'Google Ads',
    tags: ['Google Ads', 'Hospitality', 'Hotel'],
  },
  {
    id: 'real-estate-leads',
    title: 'Real Estate Lead Generation',
    industry: 'Real Estate',
    goal: 'Generate qualified buyer leads',
    strategy: 'Lookalike audiences with lead form extensions',
    results: ['500+ qualified leads/month', '38% lead-to-tour rate', '$12 cost per lead'],
    image: '/portfolio/realestate.jpg',
    category: 'Meta Ads',
    tags: ['Meta Ads', 'Real Estate', 'Lead Gen'],
  },
  {
    id: 'saas-branding',
    title: 'B2B SaaS Brand Awareness',
    industry: 'Technology',
    goal: 'Build brand awareness among decision-makers',
    strategy: 'LinkedIn Ads targeting with content marketing',
    results: ['1M+ impressions', '25% increase in website traffic', '150+ demo requests'],
    image: '/portfolio/saas.jpg',
    category: 'Social Media',
    tags: ['LinkedIn Ads', 'B2B', 'SaaS'],
  },
  {
    id: 'seo-overhaul',
    title: 'SEO Overhaul & Traffic Growth',
    industry: 'E-commerce',
    goal: 'Recover and grow organic traffic',
    strategy: 'Technical SEO fix + content cluster strategy',
    results: ['180% organic traffic increase', '50+ keywords in top 3', '3x blog revenue'],
    image: '/portfolio/seo.jpg',
    category: 'SEO',
    tags: ['SEO', 'Content', 'E-commerce'],
  },
]

export const caseStudies: CaseStudy[] = [
  {
    id: 'ecommerce-scale',
    title: 'How We Scaled an E-commerce Brand from $50K to $200K Monthly Revenue',
    client: 'FashionForward',
    industry: 'E-commerce',
    problem: 'The brand was stuck at $50K monthly revenue with rising CAC and stagnant ROAS.',
    research: 'Competitor analysis revealed untapped audience segments and creative fatigue.',
    audience: 'Fashion-conscious women 25-45, lookalikes from high-value customers, engaged shoppers.',
    campaignStructure: 'CBO with 5 ad sets per campaign, dynamic creative optimization, broad targeting.',
    creativeStrategy: 'UGC-style videos, comparison ads, lifestyle imagery, seasonal promotions.',
    budget: '$15,000/month initially, scaled to $40,000/month over 3 months.',
    optimisation: 'Daily bid adjustments, creative rotation every 5 days, audience expansion weekly.',
    finalResults: [
      'Monthly revenue grew from $50K to $200K+',
      'ROAS improved from 2.1x to 3.5x',
      'CAC decreased by 42%',
      'Scale-tested to $5K/day ad spend',
    ],
    beforeAfter: [
      { label: 'Monthly Revenue', before: '$50,000', after: '$200,000+' },
      { label: 'ROAS', before: '2.1x', after: '3.5x' },
      { label: 'Customer CAC', before: '$45', after: '$26' },
    ],
    image: '/case-studies/ecommerce.jpg',
  },
  {
    id: 'local-business-growth',
    title: 'Driving 150% More Foot Traffic for a Local Restaurant Chain',
    client: 'Bella Italia',
    industry: 'Restaurant',
    problem: 'Declining foot traffic and over-reliance on delivery platforms eating margins.',
    research: 'Customer surveys showed people wanted dine-in experiences but didn\'t know about new menu items.',
    audience: 'Foodies within 10-mile radius, past visitors, special occasion seekers.',
    campaignStructure: 'Traffic + Conversion campaigns with store location extensions.',
    creativeStrategy: 'Food photography, limited-time offers, customer testimonial videos.',
    budget: '$3,000/month across 3 locations.',
    optimisation: 'A/B tested offer types, optimized hours, adjusted geo-fencing radius.',
    finalResults: [
      '150% increase in foot traffic',
      '40% rise in direct orders',
      '2.8x ROAS across all locations',
      'Reduced delivery platform dependency by 25%',
    ],
    beforeAfter: [
      { label: 'Weekly Foot Traffic', before: '1,200', after: '3,000+' },
      { label: 'Direct Orders', before: '200/month', after: '500+/month' },
    ],
    image: '/case-studies/restaurant.jpg',
  },
]

export const stats: Stat[] = [
  { label: 'Campaigns Managed', value: 150, suffix: '+' },
  { label: 'Leads Generated', value: 25000, suffix: '+' },
  { label: 'Ad Spend Managed', value: 5, prefix: '$', suffix: 'M+' },
  { label: 'Average ROAS', value: 3.2, suffix: 'x' },
  { label: 'Clients Served', value: 50, suffix: '+' },
  { label: 'Projects Completed', value: 200, suffix: '+' },
]

export const skills: Skill[] = [
  { name: 'Meta Ads', level: 95, category: 'Paid Advertising' },
  { name: 'Google Ads', level: 90, category: 'Paid Advertising' },
  { name: 'TikTok Ads', level: 85, category: 'Paid Advertising' },
  { name: 'LinkedIn Ads', level: 80, category: 'Paid Advertising' },
  { name: 'SEO', level: 88, category: 'Organic Marketing' },
  { name: 'Content Strategy', level: 92, category: 'Organic Marketing' },
  { name: 'Blogging', level: 85, category: 'Organic Marketing' },
  { name: 'Canva', level: 90, category: 'Design' },
  { name: 'Photoshop', level: 75, category: 'Design' },
  { name: 'Figma', level: 80, category: 'Design' },
  { name: 'GA4', level: 88, category: 'Analytics' },
  { name: 'Meta Events', level: 85, category: 'Analytics' },
  { name: 'Tag Manager', level: 82, category: 'Analytics' },
  { name: 'Clarity', level: 78, category: 'Analytics' },
]

export const tools: Tool[] = [
  { name: 'Meta Business Suite', description: 'Campaign management & reporting', category: 'Advertising Platforms', proficiency: 'Expert' },
  { name: 'Meta Ads Manager', description: 'Advanced campaign optimization', category: 'Advertising Platforms', proficiency: 'Expert' },
  { name: 'Google Ads', description: 'Search, Display, Shopping, PMax', category: 'Advertising Platforms', proficiency: 'Expert' },
  { name: 'Google Analytics 4', description: 'Web analytics & audience insights', category: 'Analytics', proficiency: 'Expert' },
  { name: 'Google Tag Manager', description: 'Tag management & tracking setup', category: 'Analytics', proficiency: 'Advanced' },
  { name: 'Search Console', description: 'SEO performance monitoring', category: 'SEO', proficiency: 'Advanced' },
  { name: 'Canva', description: 'Visual content creation', category: 'Design', proficiency: 'Expert' },
  { name: 'Adobe Photoshop', description: 'Image editing & graphics', category: 'Design', proficiency: 'Advanced' },
  { name: 'CapCut', description: 'Video editing for social media', category: 'Video', proficiency: 'Advanced' },
  { name: 'Premiere Pro', description: 'Professional video editing', category: 'Video', proficiency: 'Intermediate' },
  { name: 'Notion', description: 'Project management & documentation', category: 'Productivity', proficiency: 'Expert' },
  { name: 'ChatGPT', description: 'AI copywriting & strategy', category: 'AI Tools', proficiency: 'Expert' },
  { name: 'Midjourney', description: 'AI image generation', category: 'AI Tools', proficiency: 'Advanced' },
  { name: 'Claude', description: 'AI content & analysis', category: 'AI Tools', proficiency: 'Advanced' },
  { name: 'Gemini', description: 'AI research & insights', category: 'AI Tools', proficiency: 'Intermediate' },
]

export const certifications: Certification[] = [
  { title: 'Meta Certified Digital Marketing Associate', issuer: 'Meta', date: '2024', link: '#', image: '/certs/meta.png' },
  { title: 'Google Ads Certification', issuer: 'Google', date: '2024', link: '#', image: '/certs/google.png' },
  { title: 'Google Analytics Individual Qualification', issuer: 'Google', date: '2024', link: '#', image: '/certs/ga4.png' },
  { title: 'HubSpot Content Marketing Certification', issuer: 'HubSpot', date: '2023', link: '#', image: '/certs/hubspot.png' },
  { title: 'Meta Certified Media Planning Professional', issuer: 'Meta', date: '2024', link: '#', image: '/certs/meta-media.png' },
]

export const testimonials: Testimonial[] = [
  {
    name: "Sarah Johnson",
    role: "CEO",
    company: "TrendyThreads Fashion",
    review: "Working with this team transformed our online presence. Our Meta Ads ROAS went from 2.1x to 4.8x in just 3 months. The data-driven approach and creative strategies made all the difference.",
    rating: 5,
    image: "",
  },
  {
    name: "Michael Chen",
    role: "Owner",
    company: "Golden Dragon Restaurant",
    review: "Local SEO and Google Ads expertise brought us 650+ new customers per month. The attention to detail and understanding of our local market was impressive. Highly recommend!",
    rating: 5,
    image: "",
  },
  {
    name: "Emily Rodriguez",
    role: "CMO",
    company: "CloudScale Technologies",
    review: "The SEO overhaul increased our organic traffic by 210% and we're ranking #1 for our core keywords. Strategic thinking combined with technical execution — exactly what we needed.",
    rating: 5,
    image: "",
  },
  {
    name: "David Park",
    role: "Founder",
    company: "LuxeHaven Realty",
    review: "Our Instagram grew from 2K to 25K followers in 6 months, and we sold 12 properties directly from social leads. The content strategy was creative and results-oriented.",
    rating: 5,
    image: "",
  },
  {
    name: "Jessica Williams",
    role: "Marketing Director",
    company: "GlowUp Cosmetics",
    review: "The TikTok launch campaign hit 2.3M views and sold out our first batch in a week. Truly viral marketing done right. The creator partnership strategy was genius.",
    rating: 5,
    image: "",
  },
  {
    name: "Alex Thompson",
    role: "VP Marketing",
    company: "PayFlow Fintech",
    review: "Content marketing engine delivered 250+ MQLs per month. The thought leadership content established us as industry experts. ROI has been exceptional across every channel.",
    rating: 5,
    image: "",
  },
]

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: '10 Meta Ads Strategies That Will Transform Your ROAS in 2025',
    excerpt: 'Learn the latest Meta Ads strategies that top performers use to achieve 3x+ ROAS.',
    category: 'Meta Ads',
    date: '2025-06-15',
    readTime: '8 min read',
    image: '/blog/meta-ads.jpg',
    slug: 'meta-ads-strategies-2025',
  },
  {
    id: '2',
    title: 'Instagram Growth Hacks: How We Gained 50K Followers in 30 Days',
    excerpt: 'Organic growth strategies that actually work on Instagram in 2025.',
    category: 'Instagram Growth',
    date: '2025-06-01',
    readTime: '6 min read',
    image: '/blog/instagram-growth.jpg',
    slug: 'instagram-growth-hacks',
  },
  {
    id: '3',
    title: 'Google Ads vs Meta Ads: Which Platform is Right for Your Business?',
    excerpt: 'A comprehensive comparison to help you allocate your ad budget effectively.',
    category: 'Google Ads',
    date: '2025-05-20',
    readTime: '10 min read',
    image: '/blog/google-vs-meta.jpg',
    slug: 'google-ads-vs-meta-ads',
  },
  {
    id: '4',
    title: 'The Psychology of High-Converting Ad Creatives',
    excerpt: 'Understand the psychological principles behind ads that drive action.',
    category: 'Marketing Psychology',
    date: '2025-05-10',
    readTime: '7 min read',
    image: '/blog/psychology.jpg',
    slug: 'psychology-of-ad-creatives',
  },
  {
    id: '5',
    title: 'How AI is Revolutionizing Digital Marketing in 2025',
    excerpt: 'Explore the AI tools and techniques reshaping how marketers work.',
    category: 'AI Marketing',
    date: '2025-04-28',
    readTime: '9 min read',
    image: '/blog/ai-marketing.jpg',
    slug: 'ai-revolutionizing-digital-marketing',
  },
  {
    id: '6',
    title: 'SEO Trends You Need to Know in 2025',
    excerpt: 'Stay ahead of the curve with these emerging SEO trends and algorithm updates.',
    category: 'SEO',
    date: '2025-04-15',
    readTime: '6 min read',
    image: '/blog/seo-trends.jpg',
    slug: 'seo-trends-2025',
  },
]

export const timelineEvents: TimelineEvent[] = [
  { year: '2024', title: 'Senior Marketing Consultant', description: 'Leading digital strategy for 20+ clients across e-commerce, real estate, and hospitality sectors.' },
  { year: '2023', title: 'Marketing Manager at GrowthLab', description: 'Managed $2M+ annual ad spend. Achieved 3.2x average ROAS across all campaigns.' },
  { year: '2022', title: 'Digital Marketing Specialist', description: 'Launched 100+ campaigns. Specialized in Meta Ads and Google Ads optimization.' },
  { year: '2021', title: 'Junior Marketing Analyst', description: 'Started career in data analytics. Built foundation in tracking and reporting.' },
]

export const resources = [
  { title: 'Content Calendar Template', description: 'Plan your content 30 days ahead', icon: 'Calendar', link: '#', type: 'Template' },
  { title: 'Meta Ads Checklist', description: 'Launch campaigns with confidence', icon: 'CheckSquare', link: '#', type: 'Checklist' },
  { title: 'Social Media Planner', description: 'Weekly planning for all platforms', icon: 'Share2', link: '#', type: 'Template' },
  { title: 'Marketing Audit Checklist', description: 'Evaluate your current marketing', icon: 'ClipboardCheck', link: '#', type: 'Checklist' },
  { title: 'Caption Templates', description: '100 proven caption formulas', icon: 'FileText', link: '#', type: 'Template' },
  { title: 'Video Script Templates', description: 'Hook, story, CTA in one page', icon: 'Video', link: '#', type: 'Template' },
  { title: 'Hashtag Lists', description: '1000+ hashtags by niche', icon: 'Hash', link: '#', type: 'Reference' },
]

export const clients = ['Hotel Tulip', 'Coffee O Clock', 'Aroma Hospitality', 'TUA','Moon light School', 'Urban Moter','Dalan Resort','Tulsi Traders' ]
export const industries = ['E-commerce', 'Restaurant', 'Hospitality', 'Technology', 'Real Estate', 'SaaS', 'Health & Fitness', 'Education']
